---
# Oppgaver for switcher: EtherChannel (SG3) + trunkporter (SG1)

- name: Konfigurer trunk-porter (f.eks. SG1)
  ios_config:
    lines:
      - interface {{ item.name }}
      - switchport mode trunk
      - no shutdown
  loop: "{{ trunk_ports | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
  when: trunk_ports is defined

- name: Konfigurer EtherChannel (SG3)
  ios_config:
    lines:
      - interface {{ item }}
      - channel-group {{ port_channel_id }} mode {{ port_channel_mode }}
  loop: "{{ etherchannel_members | default([]) }}"
  loop_control:
    label: "{{ item }}"
  when: etherchannel_members is defined

- name: Konfigurer Port-channel interface
  ios_config:
    lines:
      - interface Port-channel{{ port_channel_id }}
      - description EtherChannel from SG3
      - switchport mode trunk
      - no shutdown
  when: port_channel_id is defined

- name: Lagre konfig (startup-config)
  ios_config:
    save_when: modified
