---
- name: Configure interfaces and DHCP on router
  hosts: RG1
  gather_facts: no
  collections:
    - cisco.ios

  vars:
    dhcp_settings:
      pool_name: VLAN10_POOL
      network: 192.168.10.0
      netmask: 255.255.255.0
      default_router: 192.168.10.1
      dns_server: 8.8.8.8
      excluded_ips:
        - 192.168.10.1
        - 192.168.10.2

  tasks:
    - name: Configure interface Gig0/0/1
      cisco.ios.ios_config:
        lines:
          - ip address 192.168.2.1 255.255.255.0
          - no shutdown
        parents: interface Gig0/0/1

    - name: Configure interface Gig0/0/0
      cisco.ios.ios_config:
        lines:
          - ip address 192.168.0.1 255.255.255.0
          - no shutdown
        parents: interface Gig0/0/0

    - name: Configure DHCP excluded addresses
      cisco.ios.ios_config:
        lines:
          - "ip dhcp excluded-address {{ item }}"
      loop: "{{ dhcp_settings.excluded_ips }}"

    - name: Configure DHCP pool for {{ dhcp_settings.pool_name }}
      cisco.ios.ios_config:
        lines:
          - "network {{ dhcp_settings.network }} {{ dhcp_settings.netmask }}"
          - "default-router {{ dhcp_settings.default_router }}"
          - "dns-server {{ dhcp_settings.dns_server }}"
        parents:
          - "ip dhcp pool {{ dhcp_settings.pool_name }}"
